/* Generated by Yosys 0.51 (git sha1 c4b519022, x86_64-w64-mingw32-g++ 13.2.0 -O3) */

module blink(clk, tx);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire [18:0] _030_;
  wire [18:0] _031_;
  wire [18:0] _032_;
  wire [7:0] _033_;
  wire [7:0] _034_;
  wire [7:0] _035_;
  wire [2:0] _036_;
  wire [2:0] _037_;
  wire [2:0] _038_;
  wire [3:0] _039_;
  wire [3:0] _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire [3:0] _044_;
  wire [1:0] _045_;
  wire [1:0] _046_;
  wire [1:0] _047_;
  wire [1:0] _048_;
  wire [1:0] _049_;
  wire [3:0] _050_;
  wire [1:0] _051_;
  wire [3:0] \34.bit_count ;
  wire \60.Y ;
  wire [7:0] \64.B ;
  wire [3:0] \64.Y ;
  wire [18:0] baud_counter;
  wire baud_tick;
  input clk;
  wire clk;
  wire [7:0] data_counter;
  output tx;
  wire tx;
  wire [7:0] tx_data;
  CC_LUT3 #(
    .INIT(8'h70)
  ) _052_ (
    .I0(_045_[1]),
    .I1(_045_[0]),
    .I2(_032_[6]),
    .O(_017_)
  );
  CC_LUT4 #(
    .INIT(16'h8000)
  ) _053_ (
    .I0(_044_[0]),
    .I1(_044_[1]),
    .I2(_044_[2]),
    .I3(_044_[3]),
    .O(_045_[0])
  );
  CC_LUT3 #(
    .INIT(8'h80)
  ) _054_ (
    .I0(baud_counter[9]),
    .I1(baud_counter[10]),
    .I2(baud_counter[12]),
    .O(_044_[0])
  );
  CC_LUT4 #(
    .INIT(16'h0100)
  ) _055_ (
    .I0(baud_counter[0]),
    .I1(baud_counter[3]),
    .I2(baud_counter[7]),
    .I3(baud_counter[18]),
    .O(_044_[1])
  );
  CC_LUT4 #(
    .INIT(16'h0100)
  ) _056_ (
    .I0(baud_counter[1]),
    .I1(baud_counter[5]),
    .I2(baud_counter[6]),
    .I3(baud_counter[16]),
    .O(_044_[2])
  );
  CC_LUT4 #(
    .INIT(16'h0100)
  ) _057_ (
    .I0(baud_counter[8]),
    .I1(baud_counter[14]),
    .I2(baud_counter[15]),
    .I3(baud_counter[4]),
    .O(_044_[3])
  );
  CC_LUT4 #(
    .INIT(16'h0100)
  ) _058_ (
    .I0(baud_counter[11]),
    .I1(baud_counter[13]),
    .I2(baud_counter[17]),
    .I3(baud_counter[2]),
    .O(_045_[1])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _059_ (
    .I0(_049_[0]),
    .I1(_035_[5]),
    .O(_008_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _060_ (
    .I0(_048_[0]),
    .I1(_048_[1]),
    .O(_049_[0])
  );
  CC_LUT4 #(
    .INIT(16'h8000)
  ) _061_ (
    .I0(data_counter[0]),
    .I1(data_counter[6]),
    .I2(data_counter[7]),
    .I3(data_counter[1]),
    .O(_048_[0])
  );
  CC_LUT4 #(
    .INIT(16'h8000)
  ) _062_ (
    .I0(data_counter[5]),
    .I1(data_counter[4]),
    .I2(data_counter[3]),
    .I3(data_counter[2]),
    .O(_048_[1])
  );
  CC_LUT3 #(
    .INIT(8'h70)
  ) _063_ (
    .I0(_045_[1]),
    .I1(_045_[0]),
    .I2(_032_[18]),
    .O(_029_)
  );
  CC_LUT3 #(
    .INIT(8'h70)
  ) _064_ (
    .I0(_045_[1]),
    .I1(_045_[0]),
    .I2(_032_[17]),
    .O(_028_)
  );
  CC_LUT3 #(
    .INIT(8'h70)
  ) _065_ (
    .I0(_045_[1]),
    .I1(_045_[0]),
    .I2(_032_[16]),
    .O(_027_)
  );
  CC_LUT3 #(
    .INIT(8'h70)
  ) _066_ (
    .I0(_045_[1]),
    .I1(_045_[0]),
    .I2(_032_[15]),
    .O(_026_)
  );
  CC_LUT3 #(
    .INIT(8'h70)
  ) _067_ (
    .I0(_045_[1]),
    .I1(_045_[0]),
    .I2(_032_[14]),
    .O(_025_)
  );
  CC_LUT3 #(
    .INIT(8'h70)
  ) _068_ (
    .I0(_045_[1]),
    .I1(_045_[0]),
    .I2(_032_[13]),
    .O(_024_)
  );
  CC_LUT3 #(
    .INIT(8'h70)
  ) _069_ (
    .I0(_045_[1]),
    .I1(_045_[0]),
    .I2(_032_[12]),
    .O(_023_)
  );
  CC_LUT3 #(
    .INIT(8'h70)
  ) _070_ (
    .I0(_045_[1]),
    .I1(_045_[0]),
    .I2(_032_[11]),
    .O(_022_)
  );
  CC_LUT3 #(
    .INIT(8'h70)
  ) _071_ (
    .I0(_045_[1]),
    .I1(_045_[0]),
    .I2(_032_[10]),
    .O(_021_)
  );
  CC_LUT3 #(
    .INIT(8'h70)
  ) _072_ (
    .I0(_045_[1]),
    .I1(_045_[0]),
    .I2(_032_[9]),
    .O(_020_)
  );
  CC_LUT3 #(
    .INIT(8'h70)
  ) _073_ (
    .I0(_045_[1]),
    .I1(_045_[0]),
    .I2(_032_[8]),
    .O(_019_)
  );
  CC_LUT3 #(
    .INIT(8'h70)
  ) _074_ (
    .I0(_045_[1]),
    .I1(_045_[0]),
    .I2(_032_[7]),
    .O(_018_)
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _075_ (
    .I0(_049_[0]),
    .I1(_035_[4]),
    .O(_007_)
  );
  CC_LUT3 #(
    .INIT(8'h70)
  ) _076_ (
    .I0(_045_[1]),
    .I1(_045_[0]),
    .I2(_032_[5]),
    .O(_016_)
  );
  CC_LUT3 #(
    .INIT(8'h70)
  ) _077_ (
    .I0(_045_[1]),
    .I1(_045_[0]),
    .I2(_032_[4]),
    .O(_015_)
  );
  CC_LUT3 #(
    .INIT(8'h70)
  ) _078_ (
    .I0(_045_[1]),
    .I1(_045_[0]),
    .I2(_032_[3]),
    .O(_014_)
  );
  CC_LUT2 #(
    .INIT(4'h1)
  ) _079_ (
    .I0(_051_[0]),
    .I1(_046_[0]),
    .O(\60.Y )
  );
  CC_LUT4 #(
    .INIT(16'h0503)
  ) _080_ (
    .I0(_050_[0]),
    .I1(_050_[1]),
    .I2(_046_[1]),
    .I3(_038_[2]),
    .O(_051_[0])
  );
  CC_LUT4 #(
    .INIT(16'hfe00)
  ) _081_ (
    .I0(\34.bit_count [0]),
    .I1(\34.bit_count [2]),
    .I2(\34.bit_count [1]),
    .I3(\34.bit_count [3]),
    .O(_046_[1])
  );
  CC_LUT4 #(
    .INIT(16'h0001)
  ) _082_ (
    .I0(\34.bit_count [2]),
    .I1(\34.bit_count [3]),
    .I2(\34.bit_count [1]),
    .I3(\34.bit_count [0]),
    .O(_046_[0])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _083_ (
    .I0(_049_[0]),
    .I1(_035_[3]),
    .O(_006_)
  );
  CC_LUT3 #(
    .INIT(8'h70)
  ) _084_ (
    .I0(_045_[1]),
    .I1(_045_[0]),
    .I2(_032_[2]),
    .O(_013_)
  );
  CC_LUT3 #(
    .INIT(8'h70)
  ) _085_ (
    .I0(_045_[1]),
    .I1(_045_[0]),
    .I2(_032_[1]),
    .O(_012_)
  );
  CC_LUT3 #(
    .INIT(8'h70)
  ) _086_ (
    .I0(_045_[1]),
    .I1(_045_[0]),
    .I2(_032_[0]),
    .O(_011_)
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _087_ (
    .I0(_049_[0]),
    .I1(_035_[7]),
    .O(_010_)
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _088_ (
    .I0(_049_[0]),
    .I1(_035_[6]),
    .O(_009_)
  );
  CC_LUT3 #(
    .INIT(8'h0e)
  ) _089_ (
    .I0(\64.B [4]),
    .I1(_046_[0]),
    .I2(_046_[1]),
    .O(\64.Y [0])
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _090_ (
    .I0(_047_[0]),
    .I1(\64.B [5]),
    .O(\64.Y [1])
  );
  CC_LUT2 #(
    .INIT(4'h1)
  ) _091_ (
    .I0(_046_[0]),
    .I1(_046_[1]),
    .O(_047_[0])
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _092_ (
    .I0(_047_[0]),
    .I1(\64.B [6]),
    .O(\64.Y [2])
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _093_ (
    .I0(_047_[0]),
    .I1(\64.B [7]),
    .O(\64.Y [3])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _094_ (
    .I0(_049_[0]),
    .I1(_035_[2]),
    .O(_005_)
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _095_ (
    .I0(_049_[0]),
    .I1(_035_[1]),
    .O(_004_)
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _096_ (
    .I0(_049_[0]),
    .I1(_035_[0]),
    .O(_003_)
  );
  CC_LUT4 #(
    .INIT(16'h1f00)
  ) _097_ (
    .I0(\34.bit_count [2]),
    .I1(\34.bit_count [1]),
    .I2(\34.bit_count [3]),
    .I3(baud_tick),
    .O(_001_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _098_ (
    .I0(_046_[0]),
    .I1(baud_tick),
    .O(_002_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _099_ (
    .I0(_045_[0]),
    .I1(_045_[1]),
    .O(_000_)
  );
  CC_ADDF _100_ (
    .A(1'h1),
    .B(baud_counter[0]),
    .CI(1'h0),
    .CO(_030_[1]),
    .S(_032_[0])
  );
  CC_ADDF _101_ (
    .A(1'h0),
    .B(baud_counter[10]),
    .CI(_030_[10]),
    .CO(_030_[11]),
    .S(_032_[10])
  );
  CC_ADDF _102_ (
    .A(1'h0),
    .B(baud_counter[11]),
    .CI(_030_[11]),
    .CO(_030_[12]),
    .S(_032_[11])
  );
  CC_ADDF _103_ (
    .A(1'h0),
    .B(baud_counter[12]),
    .CI(_030_[12]),
    .CO(_030_[13]),
    .S(_032_[12])
  );
  CC_ADDF _104_ (
    .A(1'h0),
    .B(baud_counter[13]),
    .CI(_030_[13]),
    .CO(_030_[14]),
    .S(_032_[13])
  );
  CC_ADDF _105_ (
    .A(1'h0),
    .B(baud_counter[14]),
    .CI(_030_[14]),
    .CO(_030_[15]),
    .S(_032_[14])
  );
  CC_ADDF _106_ (
    .A(1'h0),
    .B(baud_counter[15]),
    .CI(_030_[15]),
    .CO(_030_[16]),
    .S(_032_[15])
  );
  CC_ADDF _107_ (
    .A(1'h0),
    .B(baud_counter[16]),
    .CI(_030_[16]),
    .CO(_030_[17]),
    .S(_032_[16])
  );
  CC_ADDF _108_ (
    .A(1'h0),
    .B(baud_counter[17]),
    .CI(_030_[17]),
    .CO(_030_[18]),
    .S(_032_[17])
  );
  CC_ADDF _109_ (
    .A(1'h0),
    .B(baud_counter[18]),
    .CI(_030_[18]),
    .CO(_031_[18]),
    .S(_032_[18])
  );
  CC_ADDF _110_ (
    .A(1'h0),
    .B(baud_counter[1]),
    .CI(_030_[1]),
    .CO(_030_[2]),
    .S(_032_[1])
  );
  CC_ADDF _111_ (
    .A(1'h0),
    .B(baud_counter[2]),
    .CI(_030_[2]),
    .CO(_030_[3]),
    .S(_032_[2])
  );
  CC_ADDF _112_ (
    .A(1'h0),
    .B(baud_counter[3]),
    .CI(_030_[3]),
    .CO(_030_[4]),
    .S(_032_[3])
  );
  CC_ADDF _113_ (
    .A(1'h0),
    .B(baud_counter[4]),
    .CI(_030_[4]),
    .CO(_030_[5]),
    .S(_032_[4])
  );
  CC_ADDF _114_ (
    .A(1'h0),
    .B(baud_counter[5]),
    .CI(_030_[5]),
    .CO(_030_[6]),
    .S(_032_[5])
  );
  CC_ADDF _115_ (
    .A(1'h0),
    .B(baud_counter[6]),
    .CI(_030_[6]),
    .CO(_030_[7]),
    .S(_032_[6])
  );
  CC_ADDF _116_ (
    .A(1'h0),
    .B(baud_counter[7]),
    .CI(_030_[7]),
    .CO(_030_[8]),
    .S(_032_[7])
  );
  CC_ADDF _117_ (
    .A(1'h0),
    .B(baud_counter[8]),
    .CI(_030_[8]),
    .CO(_030_[9]),
    .S(_032_[8])
  );
  CC_ADDF _118_ (
    .A(1'h0),
    .B(baud_counter[9]),
    .CI(_030_[9]),
    .CO(_030_[10]),
    .S(_032_[9])
  );
  CC_ADDF _119_ (
    .A(1'h1),
    .B(data_counter[0]),
    .CI(1'h0),
    .CO(_033_[1]),
    .S(_035_[0])
  );
  CC_ADDF _120_ (
    .A(1'h0),
    .B(data_counter[1]),
    .CI(_033_[1]),
    .CO(_033_[2]),
    .S(_035_[1])
  );
  CC_ADDF _121_ (
    .A(1'h0),
    .B(data_counter[2]),
    .CI(_033_[2]),
    .CO(_033_[3]),
    .S(_035_[2])
  );
  CC_ADDF _122_ (
    .A(1'h0),
    .B(data_counter[3]),
    .CI(_033_[3]),
    .CO(_033_[4]),
    .S(_035_[3])
  );
  CC_ADDF _123_ (
    .A(1'h0),
    .B(data_counter[4]),
    .CI(_033_[4]),
    .CO(_033_[5]),
    .S(_035_[4])
  );
  CC_ADDF _124_ (
    .A(1'h0),
    .B(data_counter[5]),
    .CI(_033_[5]),
    .CO(_033_[6]),
    .S(_035_[5])
  );
  CC_ADDF _125_ (
    .A(1'h0),
    .B(data_counter[6]),
    .CI(_033_[6]),
    .CO(_033_[7]),
    .S(_035_[6])
  );
  CC_ADDF _126_ (
    .A(1'h0),
    .B(data_counter[7]),
    .CI(_033_[7]),
    .CO(_034_[7]),
    .S(_035_[7])
  );
  CC_ADDF _127_ (
    .A(\34.bit_count [0]),
    .B(1'h0),
    .CI(1'h1),
    .CO(_036_[1]),
    .S(_038_[0])
  );
  CC_ADDF _128_ (
    .A(\34.bit_count [1]),
    .B(1'h1),
    .CI(_036_[1]),
    .CO(_036_[2]),
    .S(_038_[1])
  );
  CC_ADDF _129_ (
    .A(\34.bit_count [2]),
    .B(1'h1),
    .CI(_036_[2]),
    .CO(_037_[2]),
    .S(_038_[2])
  );
  CC_ADDF _130_ (
    .A(1'h1),
    .B(\34.bit_count [0]),
    .CI(1'h0),
    .CO(_039_[1]),
    .S(\64.B [4])
  );
  CC_ADDF _131_ (
    .A(1'h0),
    .B(\34.bit_count [1]),
    .CI(_039_[1]),
    .CO(_039_[2]),
    .S(\64.B [5])
  );
  CC_ADDF _132_ (
    .A(1'h0),
    .B(\34.bit_count [2]),
    .CI(_039_[2]),
    .CO(_039_[3]),
    .S(\64.B [6])
  );
  CC_ADDF _133_ (
    .A(1'h0),
    .B(\34.bit_count [3]),
    .CI(_039_[3]),
    .CO(_040_[3]),
    .S(\64.B [7])
  );
  CC_BUFG _134_ (
    .I(_041_),
    .O(_042_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _135_ (
    .CLK(_042_),
    .D(\60.Y ),
    .EN(_001_),
    .Q(_043_),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _136_ (
    .CLK(_042_),
    .D(\64.Y [0]),
    .EN(_001_),
    .Q(\34.bit_count [0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _137_ (
    .CLK(_042_),
    .D(\64.Y [1]),
    .EN(_001_),
    .Q(\34.bit_count [1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _138_ (
    .CLK(_042_),
    .D(\64.Y [2]),
    .EN(_001_),
    .Q(\34.bit_count [2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _139_ (
    .CLK(_042_),
    .D(\64.Y [3]),
    .EN(_001_),
    .Q(\34.bit_count [3]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _140_ (
    .CLK(_042_),
    .D(_000_),
    .EN(1'h1),
    .Q(baud_tick),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _141_ (
    .CLK(_042_),
    .D(_003_),
    .EN(baud_tick),
    .Q(data_counter[0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _142_ (
    .CLK(_042_),
    .D(_004_),
    .EN(baud_tick),
    .Q(data_counter[1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _143_ (
    .CLK(_042_),
    .D(_005_),
    .EN(baud_tick),
    .Q(data_counter[2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _144_ (
    .CLK(_042_),
    .D(_006_),
    .EN(baud_tick),
    .Q(data_counter[3]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _145_ (
    .CLK(_042_),
    .D(_007_),
    .EN(baud_tick),
    .Q(data_counter[4]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _146_ (
    .CLK(_042_),
    .D(_008_),
    .EN(baud_tick),
    .Q(data_counter[5]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _147_ (
    .CLK(_042_),
    .D(_009_),
    .EN(baud_tick),
    .Q(data_counter[6]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _148_ (
    .CLK(_042_),
    .D(_010_),
    .EN(baud_tick),
    .Q(data_counter[7]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _149_ (
    .CLK(_042_),
    .D(_011_),
    .EN(1'h1),
    .Q(baud_counter[0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _150_ (
    .CLK(_042_),
    .D(_012_),
    .EN(1'h1),
    .Q(baud_counter[1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _151_ (
    .CLK(_042_),
    .D(_013_),
    .EN(1'h1),
    .Q(baud_counter[2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _152_ (
    .CLK(_042_),
    .D(_014_),
    .EN(1'h1),
    .Q(baud_counter[3]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _153_ (
    .CLK(_042_),
    .D(_015_),
    .EN(1'h1),
    .Q(baud_counter[4]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _154_ (
    .CLK(_042_),
    .D(_016_),
    .EN(1'h1),
    .Q(baud_counter[5]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _155_ (
    .CLK(_042_),
    .D(_017_),
    .EN(1'h1),
    .Q(baud_counter[6]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _156_ (
    .CLK(_042_),
    .D(_018_),
    .EN(1'h1),
    .Q(baud_counter[7]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _157_ (
    .CLK(_042_),
    .D(_019_),
    .EN(1'h1),
    .Q(baud_counter[8]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _158_ (
    .CLK(_042_),
    .D(_020_),
    .EN(1'h1),
    .Q(baud_counter[9]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _159_ (
    .CLK(_042_),
    .D(_021_),
    .EN(1'h1),
    .Q(baud_counter[10]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _160_ (
    .CLK(_042_),
    .D(_022_),
    .EN(1'h1),
    .Q(baud_counter[11]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _161_ (
    .CLK(_042_),
    .D(_023_),
    .EN(1'h1),
    .Q(baud_counter[12]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _162_ (
    .CLK(_042_),
    .D(_024_),
    .EN(1'h1),
    .Q(baud_counter[13]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _163_ (
    .CLK(_042_),
    .D(_025_),
    .EN(1'h1),
    .Q(baud_counter[14]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _164_ (
    .CLK(_042_),
    .D(_026_),
    .EN(1'h1),
    .Q(baud_counter[15]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _165_ (
    .CLK(_042_),
    .D(_027_),
    .EN(1'h1),
    .Q(baud_counter[16]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _166_ (
    .CLK(_042_),
    .D(_028_),
    .EN(1'h1),
    .Q(baud_counter[17]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _167_ (
    .CLK(_042_),
    .D(_029_),
    .EN(1'h1),
    .Q(baud_counter[18]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _168_ (
    .CLK(_042_),
    .D(data_counter[0]),
    .EN(_002_),
    .Q(tx_data[0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _169_ (
    .CLK(_042_),
    .D(data_counter[1]),
    .EN(_002_),
    .Q(tx_data[1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _170_ (
    .CLK(_042_),
    .D(data_counter[2]),
    .EN(_002_),
    .Q(tx_data[2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _171_ (
    .CLK(_042_),
    .D(data_counter[3]),
    .EN(_002_),
    .Q(tx_data[3]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _172_ (
    .CLK(_042_),
    .D(data_counter[4]),
    .EN(_002_),
    .Q(tx_data[4]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _173_ (
    .CLK(_042_),
    .D(data_counter[5]),
    .EN(_002_),
    .Q(tx_data[5]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _174_ (
    .CLK(_042_),
    .D(data_counter[6]),
    .EN(_002_),
    .Q(tx_data[6]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _175_ (
    .CLK(_042_),
    .D(data_counter[7]),
    .EN(_002_),
    .Q(tx_data[7]),
    .SR(1'h0)
  );
  CC_MX4 _176_ (
    .D0(tx_data[0]),
    .D1(tx_data[1]),
    .D2(tx_data[2]),
    .D3(tx_data[3]),
    .S0(_038_[0]),
    .S1(_038_[1]),
    .Y(_050_[1])
  );
  CC_MX4 _177_ (
    .D0(tx_data[4]),
    .D1(tx_data[5]),
    .D2(tx_data[6]),
    .D3(tx_data[7]),
    .S0(_038_[0]),
    .S1(_038_[1]),
    .Y(_050_[0])
  );
  CC_IBUF _178_ (
    .I(clk),
    .Y(_041_)
  );
  CC_OBUF _179_ (
    .A(_043_),
    .O(tx)
  );
  assign _030_[0] = 1'h0;
  assign _031_[17:0] = _030_[18:1];
  assign _033_[0] = 1'h0;
  assign _034_[6:0] = _033_[7:1];
  assign _036_[0] = 1'h1;
  assign _037_[1:0] = _036_[2:1];
  assign _039_[0] = 1'h0;
  assign _040_[2:0] = _039_[3:1];
  assign _047_[1] = \64.B [7];
  assign _049_[1] = _035_[2];
  assign _050_[3:2] = { _038_[2], _046_[1] };
  assign _051_[1] = _046_[0];
  assign \64.B [3:0] = 4'h1;
endmodule
