/* Generated by Yosys 0.51 (git sha1 c4b519022, x86_64-w64-mingw32-g++ 13.2.0 -O3) */

module blink(CLK_10M_IN, TX_DATA_OUT);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire [17:0] _026_;
  wire [17:0] _027_;
  wire [17:0] _028_;
  wire [3:0] _029_;
  wire [3:0] _030_;
  wire [3:0] _031_;
  wire [19:0] _032_;
  wire [19:0] _033_;
  wire [3:0] _034_;
  wire [3:0] _035_;
  wire [3:0] _036_;
  wire [3:0] _037_;
  wire [9:0] _038_;
  wire [9:0] _039_;
  wire [9:0] _040_;
  wire [9:0] _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire [2:0] _052_;
  wire [3:0] _053_;
  wire _054_;
  wire [2:0] _055_;
  wire [2:0] _056_;
  wire [2:0] _057_;
  wire [2:0] _058_;
  wire [2:0] _059_;
  wire [3:0] _060_;
  wire [1:0] _061_;
  wire [2:0] _062_;
  wire [3:0] _063_;
  wire [1:0] _064_;
  wire [2:0] _065_;
  wire [3:0] _066_;
  wire [3:0] _067_;
  wire [3:0] _068_;
  wire [1:0] _069_;
  wire _070_;
  wire [2:0] _071_;
  wire [2:0] \90.Y ;
  wire [19:0] \93.A ;
  wire [19:0] \93.Y ;
  input CLK_10M_IN;
  wire CLK_10M_IN;
  output TX_DATA_OUT;
  wire TX_DATA_OUT;
  wire [9:0] bit_counter;
  wire clk_100m;
  wire [3:0] clk_half_counter;
  wire current_data_bit;
  wire [2:0] current_state;
  wire [19:0] delay_timer;
  wire pll_locked_int;
  CC_LUT2 #(
    .INIT(4'h4)
  ) _072_ (
    .I0(bit_counter[1]),
    .I1(bit_counter[0]),
    .O(_054_)
  );
  CC_LUT3 #(
    .INIT(8'h10)
  ) _073_ (
    .I0(_057_[0]),
    .I1(_037_[0]),
    .I2(bit_counter[5]),
    .O(_020_)
  );
  CC_LUT3 #(
    .INIT(8'h53)
  ) _074_ (
    .I0(_056_[0]),
    .I1(_056_[1]),
    .I2(bit_counter[4]),
    .O(_057_[0])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _075_ (
    .I0(bit_counter[0]),
    .I1(bit_counter[1]),
    .O(_070_)
  );
  CC_LUT3 #(
    .INIT(8'h10)
  ) _076_ (
    .I0(bit_counter[1]),
    .I1(bit_counter[4]),
    .I2(_071_[2]),
    .O(_021_)
  );
  CC_LUT3 #(
    .INIT(8'h10)
  ) _077_ (
    .I0(bit_counter[0]),
    .I1(bit_counter[3]),
    .I2(bit_counter[2]),
    .O(_071_[2])
  );
  CC_LUT3 #(
    .INIT(8'h4f)
  ) _078_ (
    .I0(_055_[0]),
    .I1(bit_counter[3]),
    .I2(bit_counter[4]),
    .O(_022_)
  );
  CC_LUT2 #(
    .INIT(4'h7)
  ) _079_ (
    .I0(bit_counter[1]),
    .I1(bit_counter[0]),
    .O(_055_[0])
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _080_ (
    .I0(_059_[0]),
    .I1(_059_[1]),
    .I2(_037_[3]),
    .O(_000_)
  );
  CC_LUT3 #(
    .INIT(8'hf4)
  ) _081_ (
    .I0(bit_counter[1]),
    .I1(_058_[1]),
    .I2(bit_counter[0]),
    .O(_059_[1])
  );
  CC_LUT4 #(
    .INIT(16'h4000)
  ) _082_ (
    .I0(bit_counter[2]),
    .I1(bit_counter[5]),
    .I2(bit_counter[4]),
    .I3(bit_counter[3]),
    .O(_058_[1])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _083_ (
    .I0(\90.Y [1]),
    .I1(_041_[1]),
    .O(_006_)
  );
  CC_LUT3 #(
    .INIT(8'h10)
  ) _084_ (
    .I0(current_state[1]),
    .I1(current_state[2]),
    .I2(current_state[0]),
    .O(\90.Y [1])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _085_ (
    .I0(\90.Y [1]),
    .I1(_041_[2]),
    .O(_007_)
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _086_ (
    .I0(\90.Y [1]),
    .I1(_041_[8]),
    .O(_013_)
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _087_ (
    .I0(\90.Y [1]),
    .I1(_041_[7]),
    .O(_012_)
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _088_ (
    .I0(_061_[0]),
    .I1(_031_[3]),
    .O(_019_)
  );
  CC_LUT4 #(
    .INIT(16'h1000)
  ) _089_ (
    .I0(clk_half_counter[1]),
    .I1(clk_half_counter[2]),
    .I2(clk_half_counter[3]),
    .I3(clk_half_counter[0]),
    .O(_061_[0])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _090_ (
    .I0(_061_[0]),
    .I1(_031_[2]),
    .O(_018_)
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _091_ (
    .I0(_061_[0]),
    .I1(_031_[1]),
    .O(_017_)
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _092_ (
    .I0(_061_[0]),
    .I1(_031_[0]),
    .O(_016_)
  );
  CC_LUT4 #(
    .INIT(16'h1001)
  ) _093_ (
    .I0(_053_[3]),
    .I1(\90.Y [1]),
    .I2(_068_[2]),
    .I3(current_data_bit),
    .O(_015_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _094_ (
    .I0(\90.Y [0]),
    .I1(current_state[2]),
    .O(_053_[3])
  );
  CC_LUT2 #(
    .INIT(4'h1)
  ) _095_ (
    .I0(current_state[1]),
    .I1(current_state[0]),
    .O(\90.Y [0])
  );
  CC_LUT4 #(
    .INIT(16'h001f)
  ) _096_ (
    .I0(clk_half_counter[1]),
    .I1(clk_half_counter[0]),
    .I2(clk_half_counter[2]),
    .I3(clk_half_counter[3]),
    .O(_068_[2])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _097_ (
    .I0(\90.Y [1]),
    .I1(_041_[9]),
    .O(_014_)
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _098_ (
    .I0(\90.Y [1]),
    .I1(_041_[6]),
    .O(_011_)
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _099_ (
    .I0(\90.Y [1]),
    .I1(_041_[5]),
    .O(_010_)
  );
  CC_LUT4 #(
    .INIT(16'h3500)
  ) _100_ (
    .I0(\90.Y [2]),
    .I1(_067_[1]),
    .I2(_063_[2]),
    .I3(\93.A [0]),
    .O(\93.Y [0])
  );
  CC_LUT4 #(
    .INIT(16'hf800)
  ) _101_ (
    .I0(_066_[0]),
    .I1(_066_[1]),
    .I2(_027_[17]),
    .I3(pll_locked_int),
    .O(_067_[1])
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _102_ (
    .I0(_064_[0]),
    .I1(_064_[1]),
    .O(_066_[1])
  );
  CC_LUT4 #(
    .INIT(16'h0100)
  ) _103_ (
    .I0(delay_timer[16]),
    .I1(delay_timer[0]),
    .I2(delay_timer[7]),
    .I3(delay_timer[6]),
    .O(_064_[0])
  );
  CC_LUT4 #(
    .INIT(16'h0001)
  ) _104_ (
    .I0(delay_timer[9]),
    .I1(delay_timer[19]),
    .I2(delay_timer[18]),
    .I3(delay_timer[17]),
    .O(_064_[1])
  );
  CC_LUT3 #(
    .INIT(8'h80)
  ) _105_ (
    .I0(_052_[0]),
    .I1(_052_[1]),
    .I2(_065_[2]),
    .O(_066_[0])
  );
  CC_LUT4 #(
    .INIT(16'h0001)
  ) _106_ (
    .I0(delay_timer[13]),
    .I1(delay_timer[12]),
    .I2(delay_timer[10]),
    .I3(delay_timer[11]),
    .O(_052_[0])
  );
  CC_LUT4 #(
    .INIT(16'h1000)
  ) _107_ (
    .I0(delay_timer[15]),
    .I1(delay_timer[8]),
    .I2(delay_timer[2]),
    .I3(delay_timer[5]),
    .O(_052_[1])
  );
  CC_LUT4 #(
    .INIT(16'h0001)
  ) _108_ (
    .I0(delay_timer[1]),
    .I1(delay_timer[3]),
    .I2(delay_timer[4]),
    .I3(delay_timer[14]),
    .O(_065_[2])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _109_ (
    .I0(current_state[2]),
    .I1(\90.Y [0]),
    .O(_063_[2])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _110_ (
    .I0(current_state[2]),
    .I1(current_state[1]),
    .O(\90.Y [2])
  );
  CC_LUT4 #(
    .INIT(16'h3500)
  ) _111_ (
    .I0(\90.Y [2]),
    .I1(_067_[1]),
    .I2(_063_[2]),
    .I3(\93.A [1]),
    .O(\93.Y [1])
  );
  CC_LUT4 #(
    .INIT(16'h3500)
  ) _112_ (
    .I0(\90.Y [2]),
    .I1(_067_[1]),
    .I2(_063_[2]),
    .I3(\93.A [2]),
    .O(\93.Y [2])
  );
  CC_LUT4 #(
    .INIT(16'h3500)
  ) _113_ (
    .I0(\90.Y [2]),
    .I1(_067_[1]),
    .I2(_063_[2]),
    .I3(\93.A [3]),
    .O(\93.Y [3])
  );
  CC_LUT4 #(
    .INIT(16'h3500)
  ) _114_ (
    .I0(\90.Y [2]),
    .I1(_067_[1]),
    .I2(_063_[2]),
    .I3(\93.A [4]),
    .O(\93.Y [4])
  );
  CC_LUT4 #(
    .INIT(16'h3500)
  ) _115_ (
    .I0(\90.Y [2]),
    .I1(_067_[1]),
    .I2(_063_[2]),
    .I3(\93.A [5]),
    .O(\93.Y [5])
  );
  CC_LUT4 #(
    .INIT(16'h3500)
  ) _116_ (
    .I0(\90.Y [2]),
    .I1(_067_[1]),
    .I2(_063_[2]),
    .I3(\93.A [6]),
    .O(\93.Y [6])
  );
  CC_LUT4 #(
    .INIT(16'h3500)
  ) _117_ (
    .I0(\90.Y [2]),
    .I1(_067_[1]),
    .I2(_063_[2]),
    .I3(\93.A [7]),
    .O(\93.Y [7])
  );
  CC_LUT4 #(
    .INIT(16'h3500)
  ) _118_ (
    .I0(\90.Y [2]),
    .I1(_067_[1]),
    .I2(_063_[2]),
    .I3(\93.A [8]),
    .O(\93.Y [8])
  );
  CC_LUT4 #(
    .INIT(16'h3500)
  ) _119_ (
    .I0(\90.Y [2]),
    .I1(_067_[1]),
    .I2(_063_[2]),
    .I3(\93.A [9]),
    .O(\93.Y [9])
  );
  CC_LUT4 #(
    .INIT(16'h3500)
  ) _120_ (
    .I0(\90.Y [2]),
    .I1(_067_[1]),
    .I2(_063_[2]),
    .I3(\93.A [10]),
    .O(\93.Y [10])
  );
  CC_LUT4 #(
    .INIT(16'h3500)
  ) _121_ (
    .I0(\90.Y [2]),
    .I1(_067_[1]),
    .I2(_063_[2]),
    .I3(\93.A [11]),
    .O(\93.Y [11])
  );
  CC_LUT4 #(
    .INIT(16'h3500)
  ) _122_ (
    .I0(\90.Y [2]),
    .I1(_067_[1]),
    .I2(_063_[2]),
    .I3(\93.A [12]),
    .O(\93.Y [12])
  );
  CC_LUT4 #(
    .INIT(16'h3500)
  ) _123_ (
    .I0(\90.Y [2]),
    .I1(_067_[1]),
    .I2(_063_[2]),
    .I3(\93.A [13]),
    .O(\93.Y [13])
  );
  CC_LUT4 #(
    .INIT(16'h3500)
  ) _124_ (
    .I0(\90.Y [2]),
    .I1(_067_[1]),
    .I2(_063_[2]),
    .I3(\93.A [14]),
    .O(\93.Y [14])
  );
  CC_LUT4 #(
    .INIT(16'h3500)
  ) _125_ (
    .I0(\90.Y [2]),
    .I1(_067_[1]),
    .I2(_063_[2]),
    .I3(\93.A [15]),
    .O(\93.Y [15])
  );
  CC_LUT4 #(
    .INIT(16'h3500)
  ) _126_ (
    .I0(\90.Y [2]),
    .I1(_067_[1]),
    .I2(_063_[2]),
    .I3(\93.A [16]),
    .O(\93.Y [16])
  );
  CC_LUT4 #(
    .INIT(16'h3500)
  ) _127_ (
    .I0(\90.Y [2]),
    .I1(_067_[1]),
    .I2(_063_[2]),
    .I3(\93.A [17]),
    .O(\93.Y [17])
  );
  CC_LUT4 #(
    .INIT(16'h3500)
  ) _128_ (
    .I0(\90.Y [2]),
    .I1(_067_[1]),
    .I2(_063_[2]),
    .I3(\93.A [18]),
    .O(\93.Y [18])
  );
  CC_LUT4 #(
    .INIT(16'h3500)
  ) _129_ (
    .I0(\90.Y [2]),
    .I1(_067_[1]),
    .I2(_063_[2]),
    .I3(\93.A [19]),
    .O(\93.Y [19])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _130_ (
    .I0(\90.Y [1]),
    .I1(_041_[3]),
    .O(_008_)
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _131_ (
    .I0(\90.Y [1]),
    .I1(_041_[4]),
    .O(_009_)
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _132_ (
    .I0(\90.Y [1]),
    .I1(_041_[0]),
    .O(_005_)
  );
  CC_LUT4 #(
    .INIT(16'h00fe)
  ) _133_ (
    .I0(\90.Y [2]),
    .I1(_063_[1]),
    .I2(_063_[2]),
    .I3(_063_[3]),
    .O(_003_)
  );
  CC_LUT3 #(
    .INIT(8'h70)
  ) _134_ (
    .I0(_062_[0]),
    .I1(_062_[1]),
    .I2(\90.Y [2]),
    .O(_063_[3])
  );
  CC_LUT4 #(
    .INIT(16'h0100)
  ) _135_ (
    .I0(bit_counter[6]),
    .I1(bit_counter[7]),
    .I2(bit_counter[8]),
    .I3(_060_[3]),
    .O(_062_[1])
  );
  CC_LUT4 #(
    .INIT(16'h8000)
  ) _136_ (
    .I0(bit_counter[4]),
    .I1(bit_counter[5]),
    .I2(bit_counter[2]),
    .I3(bit_counter[9]),
    .O(_060_[3])
  );
  CC_LUT3 #(
    .INIT(8'h40)
  ) _137_ (
    .I0(_055_[0]),
    .I1(_055_[1]),
    .I2(bit_counter[3]),
    .O(_062_[0])
  );
  CC_LUT4 #(
    .INIT(16'h0001)
  ) _138_ (
    .I0(clk_half_counter[1]),
    .I1(clk_half_counter[2]),
    .I2(clk_half_counter[3]),
    .I3(clk_half_counter[0]),
    .O(_055_[1])
  );
  CC_LUT4 #(
    .INIT(16'h7f00)
  ) _139_ (
    .I0(_053_[0]),
    .I1(_053_[1]),
    .I2(_053_[2]),
    .I3(_053_[3]),
    .O(_063_[1])
  );
  CC_LUT3 #(
    .INIT(8'h80)
  ) _140_ (
    .I0(_052_[0]),
    .I1(_052_[1]),
    .I2(_052_[2]),
    .O(_053_[1])
  );
  CC_LUT4 #(
    .INIT(16'h8000)
  ) _141_ (
    .I0(delay_timer[1]),
    .I1(delay_timer[3]),
    .I2(delay_timer[4]),
    .I3(delay_timer[14]),
    .O(_052_[2])
  );
  CC_LUT4 #(
    .INIT(16'h8000)
  ) _142_ (
    .I0(delay_timer[9]),
    .I1(delay_timer[19]),
    .I2(delay_timer[18]),
    .I3(delay_timer[17]),
    .O(_053_[2])
  );
  CC_LUT4 #(
    .INIT(16'h1000)
  ) _143_ (
    .I0(delay_timer[6]),
    .I1(delay_timer[7]),
    .I2(delay_timer[16]),
    .I3(delay_timer[0]),
    .O(_053_[0])
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _144_ (
    .I0(\90.Y [2]),
    .I1(_055_[1]),
    .O(_069_[0])
  );
  CC_LUT3 #(
    .INIT(8'h1e)
  ) _145_ (
    .I0(current_state[1]),
    .I1(current_state[0]),
    .I2(current_state[2]),
    .O(_001_)
  );
  CC_LUT2 #(
    .INIT(4'he)
  ) _146_ (
    .I0(_069_[0]),
    .I1(\90.Y [1]),
    .O(_004_)
  );
  CC_LUT4 #(
    .INIT(16'h000d)
  ) _147_ (
    .I0(_063_[2]),
    .I1(_067_[1]),
    .I2(_063_[1]),
    .I3(_063_[3]),
    .O(_002_)
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _148_ (
    .I0(bit_counter[0]),
    .O(_040_[0])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _149_ (
    .I0(_054_),
    .O(_023_)
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _150_ (
    .I0(_070_),
    .O(_024_)
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _151_ (
    .I0(bit_counter[6]),
    .O(_034_[0])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _152_ (
    .I0(bit_counter[7]),
    .O(_034_[1])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _153_ (
    .I0(bit_counter[8]),
    .O(_034_[2])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _154_ (
    .I0(bit_counter[1]),
    .O(_025_)
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _155_ (
    .I0(bit_counter[9]),
    .O(_034_[3])
  );
  CC_ADDF _156_ (
    .A(delay_timer[2]),
    .B(1'h0),
    .CI(1'h1),
    .CO(_026_[1]),
    .S(_028_[0])
  );
  CC_ADDF _157_ (
    .A(delay_timer[12]),
    .B(1'h1),
    .CI(_026_[10]),
    .CO(_026_[11]),
    .S(_028_[10])
  );
  CC_ADDF _158_ (
    .A(delay_timer[13]),
    .B(1'h1),
    .CI(_026_[11]),
    .CO(_026_[12]),
    .S(_028_[11])
  );
  CC_ADDF _159_ (
    .A(delay_timer[14]),
    .B(1'h1),
    .CI(_026_[12]),
    .CO(_026_[13]),
    .S(_028_[12])
  );
  CC_ADDF _160_ (
    .A(delay_timer[15]),
    .B(1'h1),
    .CI(_026_[13]),
    .CO(_026_[14]),
    .S(_028_[13])
  );
  CC_ADDF _161_ (
    .A(delay_timer[16]),
    .B(1'h1),
    .CI(_026_[14]),
    .CO(_026_[15]),
    .S(_028_[14])
  );
  CC_ADDF _162_ (
    .A(delay_timer[17]),
    .B(1'h1),
    .CI(_026_[15]),
    .CO(_026_[16]),
    .S(_028_[15])
  );
  CC_ADDF _163_ (
    .A(delay_timer[18]),
    .B(1'h1),
    .CI(_026_[16]),
    .CO(_026_[17]),
    .S(_028_[16])
  );
  CC_ADDF _164_ (
    .A(delay_timer[19]),
    .B(1'h1),
    .CI(_026_[17]),
    .CO(_027_[17]),
    .S(_028_[17])
  );
  CC_ADDF _165_ (
    .A(delay_timer[3]),
    .B(1'h1),
    .CI(_026_[1]),
    .CO(_026_[2]),
    .S(_028_[1])
  );
  CC_ADDF _166_ (
    .A(delay_timer[4]),
    .B(1'h1),
    .CI(_026_[2]),
    .CO(_026_[3]),
    .S(_028_[2])
  );
  CC_ADDF _167_ (
    .A(delay_timer[5]),
    .B(1'h0),
    .CI(_026_[3]),
    .CO(_026_[4]),
    .S(_028_[3])
  );
  CC_ADDF _168_ (
    .A(delay_timer[6]),
    .B(1'h0),
    .CI(_026_[4]),
    .CO(_026_[5]),
    .S(_028_[4])
  );
  CC_ADDF _169_ (
    .A(delay_timer[7]),
    .B(1'h1),
    .CI(_026_[5]),
    .CO(_026_[6]),
    .S(_028_[5])
  );
  CC_ADDF _170_ (
    .A(delay_timer[8]),
    .B(1'h1),
    .CI(_026_[6]),
    .CO(_026_[7]),
    .S(_028_[6])
  );
  CC_ADDF _171_ (
    .A(delay_timer[9]),
    .B(1'h1),
    .CI(_026_[7]),
    .CO(_026_[8]),
    .S(_028_[7])
  );
  CC_ADDF _172_ (
    .A(delay_timer[10]),
    .B(1'h1),
    .CI(_026_[8]),
    .CO(_026_[9]),
    .S(_028_[8])
  );
  CC_ADDF _173_ (
    .A(delay_timer[11]),
    .B(1'h1),
    .CI(_026_[9]),
    .CO(_026_[10]),
    .S(_028_[9])
  );
  CC_ADDF _174_ (
    .A(1'h1),
    .B(clk_half_counter[0]),
    .CI(1'h0),
    .CO(_029_[1]),
    .S(_031_[0])
  );
  CC_ADDF _175_ (
    .A(1'h0),
    .B(clk_half_counter[1]),
    .CI(_029_[1]),
    .CO(_029_[2]),
    .S(_031_[1])
  );
  CC_ADDF _176_ (
    .A(1'h0),
    .B(clk_half_counter[2]),
    .CI(_029_[2]),
    .CO(_029_[3]),
    .S(_031_[2])
  );
  CC_ADDF _177_ (
    .A(1'h0),
    .B(clk_half_counter[3]),
    .CI(_029_[3]),
    .CO(_030_[3]),
    .S(_031_[3])
  );
  CC_ADDF _178_ (
    .A(1'h1),
    .B(delay_timer[0]),
    .CI(1'h0),
    .CO(_032_[1]),
    .S(\93.A [0])
  );
  CC_ADDF _179_ (
    .A(1'h0),
    .B(delay_timer[10]),
    .CI(_032_[10]),
    .CO(_032_[11]),
    .S(\93.A [10])
  );
  CC_ADDF _180_ (
    .A(1'h0),
    .B(delay_timer[11]),
    .CI(_032_[11]),
    .CO(_032_[12]),
    .S(\93.A [11])
  );
  CC_ADDF _181_ (
    .A(1'h0),
    .B(delay_timer[12]),
    .CI(_032_[12]),
    .CO(_032_[13]),
    .S(\93.A [12])
  );
  CC_ADDF _182_ (
    .A(1'h0),
    .B(delay_timer[13]),
    .CI(_032_[13]),
    .CO(_032_[14]),
    .S(\93.A [13])
  );
  CC_ADDF _183_ (
    .A(1'h0),
    .B(delay_timer[14]),
    .CI(_032_[14]),
    .CO(_032_[15]),
    .S(\93.A [14])
  );
  CC_ADDF _184_ (
    .A(1'h0),
    .B(delay_timer[15]),
    .CI(_032_[15]),
    .CO(_032_[16]),
    .S(\93.A [15])
  );
  CC_ADDF _185_ (
    .A(1'h0),
    .B(delay_timer[16]),
    .CI(_032_[16]),
    .CO(_032_[17]),
    .S(\93.A [16])
  );
  CC_ADDF _186_ (
    .A(1'h0),
    .B(delay_timer[17]),
    .CI(_032_[17]),
    .CO(_032_[18]),
    .S(\93.A [17])
  );
  CC_ADDF _187_ (
    .A(1'h0),
    .B(delay_timer[18]),
    .CI(_032_[18]),
    .CO(_032_[19]),
    .S(\93.A [18])
  );
  CC_ADDF _188_ (
    .A(1'h0),
    .B(delay_timer[19]),
    .CI(_032_[19]),
    .CO(_033_[19]),
    .S(\93.A [19])
  );
  CC_ADDF _189_ (
    .A(1'h0),
    .B(delay_timer[1]),
    .CI(_032_[1]),
    .CO(_032_[2]),
    .S(\93.A [1])
  );
  CC_ADDF _190_ (
    .A(1'h0),
    .B(delay_timer[2]),
    .CI(_032_[2]),
    .CO(_032_[3]),
    .S(\93.A [2])
  );
  CC_ADDF _191_ (
    .A(1'h0),
    .B(delay_timer[3]),
    .CI(_032_[3]),
    .CO(_032_[4]),
    .S(\93.A [3])
  );
  CC_ADDF _192_ (
    .A(1'h0),
    .B(delay_timer[4]),
    .CI(_032_[4]),
    .CO(_032_[5]),
    .S(\93.A [4])
  );
  CC_ADDF _193_ (
    .A(1'h0),
    .B(delay_timer[5]),
    .CI(_032_[5]),
    .CO(_032_[6]),
    .S(\93.A [5])
  );
  CC_ADDF _194_ (
    .A(1'h0),
    .B(delay_timer[6]),
    .CI(_032_[6]),
    .CO(_032_[7]),
    .S(\93.A [6])
  );
  CC_ADDF _195_ (
    .A(1'h0),
    .B(delay_timer[7]),
    .CI(_032_[7]),
    .CO(_032_[8]),
    .S(\93.A [7])
  );
  CC_ADDF _196_ (
    .A(1'h0),
    .B(delay_timer[8]),
    .CI(_032_[8]),
    .CO(_032_[9]),
    .S(\93.A [8])
  );
  CC_ADDF _197_ (
    .A(1'h0),
    .B(delay_timer[9]),
    .CI(_032_[9]),
    .CO(_032_[10]),
    .S(\93.A [9])
  );
  CC_ADDF _198_ (
    .A(1'h0),
    .B(_034_[0]),
    .CI(1'h1),
    .CO(_035_[1]),
    .S(_037_[0])
  );
  CC_ADDF _199_ (
    .A(1'h0),
    .B(_034_[1]),
    .CI(_035_[1]),
    .CO(_035_[2]),
    .S(_037_[1])
  );
  CC_ADDF _200_ (
    .A(1'h0),
    .B(_034_[2]),
    .CI(_035_[2]),
    .CO(_035_[3]),
    .S(_037_[2])
  );
  CC_ADDF _201_ (
    .A(1'h1),
    .B(_034_[3]),
    .CI(_035_[3]),
    .CO(_036_[3]),
    .S(_037_[3])
  );
  CC_ADDF _202_ (
    .A(1'h1),
    .B(bit_counter[0]),
    .CI(1'h0),
    .CO(_038_[1]),
    .S(_041_[0])
  );
  CC_ADDF _203_ (
    .A(1'h0),
    .B(bit_counter[1]),
    .CI(_038_[1]),
    .CO(_038_[2]),
    .S(_041_[1])
  );
  CC_ADDF _204_ (
    .A(1'h0),
    .B(bit_counter[2]),
    .CI(_038_[2]),
    .CO(_038_[3]),
    .S(_041_[2])
  );
  CC_ADDF _205_ (
    .A(1'h0),
    .B(bit_counter[3]),
    .CI(_038_[3]),
    .CO(_038_[4]),
    .S(_041_[3])
  );
  CC_ADDF _206_ (
    .A(1'h0),
    .B(bit_counter[4]),
    .CI(_038_[4]),
    .CO(_038_[5]),
    .S(_041_[4])
  );
  CC_ADDF _207_ (
    .A(1'h0),
    .B(bit_counter[5]),
    .CI(_038_[5]),
    .CO(_038_[6]),
    .S(_041_[5])
  );
  CC_ADDF _208_ (
    .A(1'h0),
    .B(bit_counter[6]),
    .CI(_038_[6]),
    .CO(_038_[7]),
    .S(_041_[6])
  );
  CC_ADDF _209_ (
    .A(1'h0),
    .B(bit_counter[7]),
    .CI(_038_[7]),
    .CO(_038_[8]),
    .S(_041_[7])
  );
  CC_ADDF _210_ (
    .A(1'h0),
    .B(bit_counter[8]),
    .CI(_038_[8]),
    .CO(_038_[9]),
    .S(_041_[8])
  );
  CC_ADDF _211_ (
    .A(1'h0),
    .B(bit_counter[9]),
    .CI(_038_[9]),
    .CO(_039_[9]),
    .S(_041_[9])
  );
  CC_BUFG _212_ (
    .I(_042_),
    .O(clk_100m)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _213_ (
    .CLK(clk_100m),
    .D(_005_),
    .EN(_004_),
    .Q(bit_counter[0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _214_ (
    .CLK(clk_100m),
    .D(_006_),
    .EN(_004_),
    .Q(bit_counter[1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _215_ (
    .CLK(clk_100m),
    .D(_007_),
    .EN(_004_),
    .Q(bit_counter[2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _216_ (
    .CLK(clk_100m),
    .D(_008_),
    .EN(_004_),
    .Q(bit_counter[3]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _217_ (
    .CLK(clk_100m),
    .D(_009_),
    .EN(_004_),
    .Q(bit_counter[4]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _218_ (
    .CLK(clk_100m),
    .D(_010_),
    .EN(_004_),
    .Q(bit_counter[5]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _219_ (
    .CLK(clk_100m),
    .D(_011_),
    .EN(_004_),
    .Q(bit_counter[6]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _220_ (
    .CLK(clk_100m),
    .D(_012_),
    .EN(_004_),
    .Q(bit_counter[7]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _221_ (
    .CLK(clk_100m),
    .D(_013_),
    .EN(_004_),
    .Q(bit_counter[8]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _222_ (
    .CLK(clk_100m),
    .D(_014_),
    .EN(_004_),
    .Q(bit_counter[9]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _223_ (
    .CLK(clk_100m),
    .D(\90.Y [0]),
    .EN(_002_),
    .Q(current_state[0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _224_ (
    .CLK(clk_100m),
    .D(\90.Y [1]),
    .EN(_002_),
    .Q(current_state[1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _225_ (
    .CLK(clk_100m),
    .D(\90.Y [2]),
    .EN(_002_),
    .Q(current_state[2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _226_ (
    .CLK(clk_100m),
    .D(_015_),
    .EN(_001_),
    .Q(_049_),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _227_ (
    .CLK(clk_100m),
    .D(_016_),
    .EN(1'h1),
    .Q(clk_half_counter[0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _228_ (
    .CLK(clk_100m),
    .D(_017_),
    .EN(1'h1),
    .Q(clk_half_counter[1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _229_ (
    .CLK(clk_100m),
    .D(_018_),
    .EN(1'h1),
    .Q(clk_half_counter[2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _230_ (
    .CLK(clk_100m),
    .D(_019_),
    .EN(1'h1),
    .Q(clk_half_counter[3]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _231_ (
    .CLK(clk_100m),
    .D(\93.Y [0]),
    .EN(_003_),
    .Q(delay_timer[0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _232_ (
    .CLK(clk_100m),
    .D(\93.Y [1]),
    .EN(_003_),
    .Q(delay_timer[1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _233_ (
    .CLK(clk_100m),
    .D(\93.Y [2]),
    .EN(_003_),
    .Q(delay_timer[2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _234_ (
    .CLK(clk_100m),
    .D(\93.Y [3]),
    .EN(_003_),
    .Q(delay_timer[3]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _235_ (
    .CLK(clk_100m),
    .D(\93.Y [4]),
    .EN(_003_),
    .Q(delay_timer[4]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _236_ (
    .CLK(clk_100m),
    .D(\93.Y [5]),
    .EN(_003_),
    .Q(delay_timer[5]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _237_ (
    .CLK(clk_100m),
    .D(\93.Y [6]),
    .EN(_003_),
    .Q(delay_timer[6]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _238_ (
    .CLK(clk_100m),
    .D(\93.Y [7]),
    .EN(_003_),
    .Q(delay_timer[7]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _239_ (
    .CLK(clk_100m),
    .D(\93.Y [8]),
    .EN(_003_),
    .Q(delay_timer[8]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _240_ (
    .CLK(clk_100m),
    .D(\93.Y [9]),
    .EN(_003_),
    .Q(delay_timer[9]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _241_ (
    .CLK(clk_100m),
    .D(\93.Y [10]),
    .EN(_003_),
    .Q(delay_timer[10]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _242_ (
    .CLK(clk_100m),
    .D(\93.Y [11]),
    .EN(_003_),
    .Q(delay_timer[11]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _243_ (
    .CLK(clk_100m),
    .D(\93.Y [12]),
    .EN(_003_),
    .Q(delay_timer[12]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _244_ (
    .CLK(clk_100m),
    .D(\93.Y [13]),
    .EN(_003_),
    .Q(delay_timer[13]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _245_ (
    .CLK(clk_100m),
    .D(\93.Y [14]),
    .EN(_003_),
    .Q(delay_timer[14]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _246_ (
    .CLK(clk_100m),
    .D(\93.Y [15]),
    .EN(_003_),
    .Q(delay_timer[15]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _247_ (
    .CLK(clk_100m),
    .D(\93.Y [16]),
    .EN(_003_),
    .Q(delay_timer[16]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _248_ (
    .CLK(clk_100m),
    .D(\93.Y [17]),
    .EN(_003_),
    .Q(delay_timer[17]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _249_ (
    .CLK(clk_100m),
    .D(\93.Y [18]),
    .EN(_003_),
    .Q(delay_timer[18]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _250_ (
    .CLK(clk_100m),
    .D(\93.Y [19]),
    .EN(_003_),
    .Q(delay_timer[19]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _251_ (
    .CLK(clk_100m),
    .D(_000_),
    .EN(_069_[0]),
    .Q(current_data_bit),
    .SR(1'h0)
  );
  CC_MX4 _252_ (
    .D0(_025_),
    .D1(1'h0),
    .D2(_024_),
    .D3(_055_[0]),
    .S0(bit_counter[2]),
    .S1(bit_counter[3]),
    .Y(_056_[1])
  );
  CC_MX4 _253_ (
    .D0(_023_),
    .D1(_040_[0]),
    .D2(bit_counter[0]),
    .D3(_055_[0]),
    .S0(bit_counter[2]),
    .S1(bit_counter[3]),
    .Y(_056_[0])
  );
  CC_MX4 _254_ (
    .D0(_070_),
    .D1(bit_counter[1]),
    .D2(_054_),
    .D3(bit_counter[0]),
    .S0(bit_counter[3]),
    .S1(bit_counter[4]),
    .Y(_051_)
  );
  CC_MX4 _255_ (
    .D0(_051_),
    .D1(_021_),
    .D2(1'h1),
    .D3(_022_),
    .S0(bit_counter[5]),
    .S1(_037_[0]),
    .Y(_050_)
  );
  CC_MX4 _256_ (
    .D0(_020_),
    .D1(1'h0),
    .D2(1'h0),
    .D3(_050_),
    .S0(_037_[1]),
    .S1(_037_[2]),
    .Y(_059_[0])
  );
  CC_IBUF _257_ (
    .I(CLK_10M_IN),
    .Y(_048_)
  );
  CC_OBUF _258_ (
    .A(_049_),
    .O(TX_DATA_OUT)
  );
  CC_PLL #(
    .CI_FILTER_CONST(32'd2),
    .CP_FILTER_CONST(32'd4),
    .LOW_JITTER(32'd1),
    .OUT_CLK("100.0"),
    .PERF_MD("ECONOMY"),
    .REF_CLK("10.0")
  ) pll_inst (
    .CLK0(_042_),
    .CLK180(_045_),
    .CLK270(_046_),
    .CLK90(_044_),
    .CLK_FEEDBACK(1'h0),
    .CLK_REF(_048_),
    .CLK_REF_OUT(_047_),
    .USR_CLK_REF(1'h0),
    .USR_LOCKED_STDY_RST(1'h0),
    .USR_PLL_LOCKED(pll_locked_int),
    .USR_PLL_LOCKED_STDY(_043_)
  );
  assign _032_[0] = 1'h0;
  assign _033_[18:0] = _032_[19:1];
  assign _035_[0] = 1'h1;
  assign _036_[2:0] = _035_[3:1];
  assign _038_[0] = 1'h0;
  assign _039_[8:0] = _038_[9:1];
  assign _040_[9:1] = bit_counter[9:1];
  assign _055_[2] = bit_counter[3];
  assign _056_[2] = bit_counter[4];
  assign _057_[2:1] = { bit_counter[5], _037_[0] };
  assign { _058_[2], _058_[0] } = { bit_counter[0], bit_counter[1] };
  assign _059_[2] = _037_[3];
  assign _060_[2:0] = bit_counter[8:6];
  assign _061_[1] = _031_[0];
  assign _062_[2] = \90.Y [2];
  assign _063_[0] = \90.Y [2];
  assign _065_[1:0] = _052_[1:0];
  assign _066_[3:2] = { pll_locked_int, _027_[17] };
  assign { _067_[3:2], _067_[0] } = { \93.A [0], _063_[2], \90.Y [2] };
  assign { _068_[3], _068_[1:0] } = { current_data_bit, \90.Y [1], _053_[3] };
  assign _069_[1] = \90.Y [1];
  assign _071_[1:0] = { bit_counter[4], bit_counter[1] };
  assign _030_[2:0] = _029_[3:1];
  assign _029_[0] = 1'h0;
  assign _027_[16:0] = _026_[17:1];
  assign _026_[0] = 1'h1;
endmodule
