#!/usr/bin/env python3
# send_hello_mod100.py
# How To Use
# sudo tcpdump -i enp0s31f6 -s 0 -XX -nn "ether proto 0x88b5" -c 5

# Script generated by Georgi Petrov to produce a known Ethernet frame on a Linux machine.
# Windows's socket API exposes from L3 and above, thus this can not work on Windows.

import argparse
import signal
import socket
import struct
import sys
import time

parser = argparse.ArgumentParser()
parser.add_argument("--iface", default="enp0s31f6")
parser.add_argument("--interval", type=float, default=1.0)
parser.add_argument(
    "--count", type=int, default=0, help="0 = endless (but counter cycles 0..99)"
)
parser.add_argument("--dst", default="ff:ff:ff:ff:ff:ff")
parser.add_argument("--ethertype", type=lambda x: int(x, 0), default=0x88B5)
args = parser.parse_args()

iface = args.iface
interval = args.interval
total = args.count
dst_mac = args.dst
ethertype = args.ethertype

# read source MAC
try:
    with open(f"/sys/class/net/{iface}/address", "r") as f:
        src_mac = f.read().strip()
except Exception as e:
    print("Не мога да прочета MAC:", e)
    sys.exit(1)


def mac_to_bytes(mac):
    return bytes.fromhex(mac.replace(":", ""))


dst = mac_to_bytes(dst_mac)
src = mac_to_bytes(src_mac)
eth = struct.pack("!H", ethertype)

HELLO = b"HELLO "  # 6 bytes
if len(HELLO) != 6:
    raise SystemExit("HELLO must be 5 bytes")

# payload layout (total payload = 46 bytes):
# [0..5]   HELLO (6)
# [6..8]   DEC3  (3 ASCII digits, zero-padded) e.g. '000'
# [9]      space ' '
# [10..17]  BIN8  (8 ASCII '0'/'1', zero-padded) e.g. '00000000'
# [18]     space ' '
# [19..20] HEX2  (2 ASCII hex digits, zero-padded) e.g. '00'
# [21..45] padding zeros

PAD_LEN = 46 - (5 + 3 + 1 + 8 + 1 + 2)  # should be >=0
if PAD_LEN < 0:
    raise SystemExit("Payload layout exceeds 46 bytes")

# socket
try:
    s = socket.socket(socket.AF_PACKET, socket.SOCK_RAW)
    s.bind((iface, 0))
except PermissionError:
    print("Run as root (sudo).")
    sys.exit(1)
except Exception as e:
    print("Binding error:", e)
    sys.exit(1)

stop = False


def handler(sig, frame):
    global stop
    stop = True


signal.signal(signal.SIGINT, handler)

seq = 0
sent = 0
print(
    f"Sending on {iface} src={src_mac} dst={dst_mac} eth=0x{ethertype:04x} every {interval}s (counter cycles 000..099)"
)
try:
    while not stop and (total == 0 or sent < total):
        # compute counter in 0..99
        val = seq % 100
        dec3 = f"{val:03d}".encode("ascii")  # 3 ASCII digits
        bin8 = f"{val:08b}".encode("ascii")  # 8 ASCII bits
        hex2 = f"{val:02X}".encode("ascii")  # 2 ASCII hex digits (uppercase)
        payload = HELLO + dec3 + b" " + bin8 + b" " + hex2 + (b"\x00" * PAD_LEN)
        frame = dst + src + eth + payload  # DA(6)+SA(6)+eth(2)+payload(46) = 60 bytes
        s.send(frame)
        sent += 1
        seq += 1
        print(
            f"{time.strftime('%Y-%m-%d %H:%M:%S')} Sent #{sent} seq_mod100={val:03d} DEC={dec3.decode()} BIN={bin8.decode()} HEX={hex2.decode()}"
        )
        time.sleep(interval)
except KeyboardInterrupt:
    pass
finally:
    s.close()
    print("Stopped. Sent:", sent)
